# The RAGFlow team do not actively maintain docker-compose-gpu.yml, so use them at your own risk. 
# Pull requests to improve it are welcome.
# include:
#   - ./docker-compose-base.yml

services:
  ragflow:
    # depends_on:
    #   mysql:
    #     condition: service_healthy
    image: ${RAGFLOW_IMAGE}
    container_name: RAGFlow
    ports:
      - ${SVR_HTTP_PORT}:9380
      - 19381:80
      - 19382:443
    volumes:
      - ./ragflow-logs:/ragflow/logs
      - ./nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    env_file: .env
    privileged: true
    pids_limit: 2048
    environment:
      - TZ=${TIMEZONE}
      - HOST_OS=Unraid
      - HOST_HOSTNAME=GZGG-Tower
      - HOST_CONTAINERNAME=RAGFlow
      # - HF_ENDPOINT=${HF_ENDPOINT}
      # - MACOS=${MACOS}
    # networks:
    #   - ragflow
    # restart: on-failure
    # https://docs.docker.com/engine/daemon/prometheus/#create-a-prometheus-configuration
    # If you're using Docker Desktop, the --add-host flag is optional. This flag makes sure that the host's internal IP gets exposed to the Prometheus container.
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.webui=http://[IP]:[PORT:19381]
      - net.unraid.docker.icon=https://github.com/gzers/HD-Icons/blob/gzers-new/border-radius/RAGFlow_A.png?raw=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
